
# Lesson 8.0.0: Store this notebook! 


Go to "File" and make sure you store this file as a local copy to your Google Drive. If you do not have a Google account and also do not want to create one, please check Option *B* below. 

Option A) Google Drive WITH collaboration

If you want to work in a collaborative manner where each of you in the group can see each other's contributions, one of you needs to store the notebook in Google Drive and share it with the others. You share it by clicking on the SHARE button on the top right of this page and share the link with the "everyone who receives this link can edit" option with the other team members per e-mail, skype, or any other way you prefer.

If you work with others, keep in mind to always copy the code before you edit it and always indicate your name as a comment (e.g. #Dagmar ) in the cell that it is clear who wrote which part. I also recommend creating a new code cell for your contributions.

Option B) Download this notebook as ipynb (Jupyter notebook) or py (Python file)

To run either of these on your local machine requires the installation of the required programs, which for the first tutorial are Python and NLTK. This will become more as we continue on to machine learning (requiring sklearn) and deep learning (requiring tensorflow and/or pytorch). In Google Codelab all of these are provided and do not need to be installed locally.

## License stuff
This excercise is based on the Semantic Computing Course by [Dagmar Grohmann](https://github.com/dgromann/SemComp_WS2018).



# Lesson 8.1: Pytorch tutorial - basics

In order to get started with deep learning and practically code up neural networks, we need to familiarize ourselves with the packages that can be used to this end. There are two basic open source machine learning frameworks that can be used to this end: 

*   TensorFlow (Google)
*   Torch (Facebook, Google DeepMind, Twitter)

Since these are high level core libraries, it is easier to use a framework that builds on top of it and adds some usability and documentation. We are going to for once not use the Google solution, but will go with the Facebook solution of Pytorch. This first part of today's tutorial will introduce you to some core concepts of Pytorch before we start working with embeddings.





In [ ]:
# Let's first install pytorch 
!pip3 install torch torchvision tqdm gensim

The most basic and important concept in Pytorch is that of a **Tensor**, To speed up computation and offer more flexibility, pytorch replaces numpy arrays with tensors.

In [ ]:
import torch
import numpy 
import tqdm

# Seed for random number generator to ensure reproducibility of
# random initializations
torch.manual_seed(1)

#Difference between tensor and numpy array
a = torch.ones(5)
print("Tensor: ")
print(a)
print("Numpy array: ")
print(a.numpy(), "\n")


# This creates a randomly initialized 5 x 3 matrix
rand = torch.rand(5,3)
print("Randomly initialized tensor: ", rand, "\n")

# This creates a 5 x 3 matriy filled with zeros and of dtype long
# There are eight datatypes in tensor, this one is a datatype of 64-bit integer (signed)
# Here are the others: https://pytorch.org/docs/stable/tensors.html
zeros = torch.zeros(5,3, dtype=torch.long)
print("Tensor initialized with zeros: ", zeros, "\n")

# Directly initialize a tensor with data 
data = torch.tensor([5.5, 3])
print("Tensor initilialized with data: ", data, "\n")

# You can redefine an existing tensor 
redefined = rand.new_ones(5, 3, dtype=torch.double)
print("Redefined randomly initialized tensor: ", redefined, "\n")

redefined_too = torch.rand_like(redefined, dtype=torch.float)
print("Initializing randomly based on the size of redefined: ", redefined_too, "\n")


# Get the size - this is actually a tuple that supports tuple operations 
print(redefined_too.size(), "\n")

Tensor: 
tensor([1., 1., 1., 1., 1.])
Numpy array: 
[1. 1. 1. 1. 1.] 

Randomly initialized tensor:  tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635]]) 

Tensor initialized with zeros:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 

Tensor initilialized with data:  tensor([5.5000, 3.0000]) 

Redefined randomly initialized tensor:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 

Initializing randomly based on the size of redefined:  tensor([[0.4550, 0.5725, 0.4980],
        [0.9371, 0.6556, 0.3138],
        [0.1980, 0.4162, 0.2843],
        [0.3398, 0.5239, 0.7981],
        [0.7718, 0.0112, 0.8100]]) 

torch.Size([5, 3]) 



Tensors in torch also support basic operations: 

In [ ]:
# Addition of tensors matching in size
x = torch.rand(5, 3)
y= torch.rand(5, 3)
print("Addition: ", x + y, "\n")
print("Addition alternative syntax: ", torch.add(x, y), "\n")

# Addition with providing a tensor as argument
result = torch.empty(5, 3)
print("Addition with tensor as argument: ", torch.add(x, y, out=result), "\n")


Addition:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]]) 

Addition alternative syntax:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]]) 

Addition with tensor as argument:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]]) 



All opreations that mutate a tensor are indicated with an underscore _ such as the example below:

In [ ]:
# add x to y
y.add_(x)
print("Adding x to y: ", y)

# you can also add a number 
print("Adding 1: ", y.add_(1))


Adding x to y:  tensor([[1.3967, 1.2089, 1.4771],
        [0.4001, 0.4698, 0.2781],
        [1.2007, 1.1880, 1.0924],
        [1.2657, 1.8914, 0.7650],
        [1.0412, 1.3104, 0.8918]])
Adding 1:  tensor([[2.3967, 2.2089, 2.4771],
        [1.4001, 1.4698, 1.2781],
        [2.2007, 2.1880, 2.0924],
        [2.2657, 2.8914, 1.7650],
        [2.0412, 2.3104, 1.8918]])


Indexing operations of tensors follow the numpy standard:

In [ ]:
# Indexing
print("X: ", x, "\n")
print("Element at index one of each row of the matrix ", x[:, 1], "\n")

X:  tensor([[0.6397, 0.9743, 0.8300],
        [0.0444, 0.0246, 0.2588],
        [0.9391, 0.4167, 0.7140],
        [0.2676, 0.9906, 0.2885],
        [0.8750, 0.5059, 0.2366]]) 

Element at index one of each row of the matrix  tensor([0.9743, 0.0246, 0.4167, 0.9906, 0.5059]) 



Resizing: if you wish to change the shape of the tensor you can use torch.view:

In [ ]:
# Exercise: resizing: what effect do the following
# resize operations have on the tensors
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print("Resizing: ")
print("Original")
print(x)
print("Resized view(16)", y, "\n")
print("Resized view(-1, 8)", z, "\n")

Resizing: 
Original
tensor([[ 0.4533,  1.1422,  0.2486, -1.7754],
        [-0.0255, -1.0233, -0.5962, -1.0055],
        [ 0.4285,  1.4761, -1.7869,  1.6103],
        [-0.7040, -0.1853, -0.9962, -0.8313]])
Resized view(16) tensor([ 0.4533,  1.1422,  0.2486, -1.7754, -0.0255, -1.0233, -0.5962, -1.0055,
         0.4285,  1.4761, -1.7869,  1.6103, -0.7040, -0.1853, -0.9962, -0.8313]) 

Resized view(-1, 8) tensor([[ 0.4533,  1.1422,  0.2486, -1.7754, -0.0255, -1.0233, -0.5962, -1.0055],
        [ 0.4285,  1.4761, -1.7869,  1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]) 



**Gradients and Backpropagation**

If you set the flag  ```.requires_grad``` on a ```torch.Tensor``` to ```True``` the program will track all operations on it in order to enable later operations, such as backpropagation, which is very important to neural networks. 

When you finish all computations on your tensor, you can then simply call the function ```.backward()``` and have all the gradients computed automatically.. The gradient will then automatically be accumulated in the attribute ```.grad```. 

If you wish to disconnect a specific tensor from this process of tracking all operations, you can call the function ```.detach()```. This prevents future computations from being tracked. You can alternatively wrap the code block in a function ```with torch.no_grad()``` which does not track the operations on any variables included in the block. This is particularly helpful if you wish to evaluate a model that has trainable parameters with *required_grad=True* flags but for which we don't need the gradients in evaluation. 

There’s one more class which is very important for autograd implementation - a `Function`.

`Tensor` and `Function` are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a `.grad_fn` attribute that references a Function that has created the `Tensor` (except for Tensors created by the user - their grad_fn is None).

If you want to compute the derivatives, you can call `.backward() `on a `Tensor`. If `Tensor` is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to `backward()`, however if it has more elements, you need to specify a `gradient` argument that is a tensor of matching shape.



In [ ]:
# Tensor that requires gradien = operations are being tracked 
x = torch.ones(2, 2, requires_grad=True)
print(x)

# Let's do some operation 
y = x + 2 
print(y)

# y was created that has a grad_fn 
print(y.grad_fn)

# Some more operations 
z = y * y * 3
out = z.mean()

print(z, out)


# Gradients
# Let's calculate and print the gradietn (d(out)/dx) and print it
out.backward()
print(x.grad)

# Stop autograd from tracking 
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)
    

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
True
True
False


# Lesson 8.2:  Word Embeddings - first steps

We will start looking at Pytorch and then play with existing embeddings. 

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Again random number generator to ensure reproducibility
torch.manual_seed(1)

Here is a mini-example of how to initialize the layer randomly and with only two words.

In [ ]:
# Map words to index to produce one-hot encodings 
word_to_ix = {"hello": 0, "world": 1}

# Initialize the embedding layer (nn = neural network) with the number of the 
# vocabulary and the dimensionality of the vectors 
# here: two words, vectors of 5 dimensions as ouput
embeds = nn.Embedding(2, 5) 
lookup_tensor = torch.tensor(list(word_to_ix.values()), dtype=torch.long)

# Create a look up tensor for the random embeddings
#for key, index in word_to_ix.items(): 
embeddings = embeds(lookup_tensor)
print(embeddings)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631]],
       grad_fn=<EmbeddingBackward0>)


Let's train our first embeddings. What do SGD and lr mean in the code below? What happens if you increase lr and 
increase the number of iterations?

The below implementation is just a toy implementation. For a better version, see [this word2vec implementation in Pytorch](https://adoni.github.io/2017/11/08/word2vec-pytorch/)

## 8.2.1 Simple Training language
We start by defining our own simple training language. Our language only contains words like "aaa", "bbb", "ccc" , … "xxx", "yyy", "zzz". The sentences contain words, whose charachters are close in alphabet. In the resulting word embedding the vectors of "aaa" should be closest to "bbb" and furthest away from "zzz".

In [ ]:
import string
from random import choice
def generate_simple_language_corpus(SENTENCE_NUMBER=500, SENTENCE_LENGTH=7):
  alpha_d = dict.fromkeys(string.ascii_lowercase, 0)

  vocab_dataset = {}
  for c, l in enumerate(alpha_d, 0):
      vocab_dataset[c] = l*3

  prev_word = None
  simple_language_text =""

  for s in range(SENTENCE_NUMBER):
      sentence = []
      start_word = choice(range(0, 18))
      for w in range(0, SENTENCE_LENGTH):
          i = choice([x for x in range(start_word+w+0, start_word+w+3) if x not in [prev_word]])
          sentence.append(vocab_dataset[i])
          prev_word = i
      simple_language_text += " ".join(sentence) + "\n"

  return simple_language_text

print(generate_simple_language_corpus(SENTENCE_NUMBER=10, SENTENCE_LENGTH=7))

rrr sss ttt www xxx yyy xxx
ddd ccc ddd ggg hhh ggg iii
ooo nnn ooo ppp rrr sss ttt
jjj kkk lll mmm lll nnn ooo
nnn ppp qqq rrr sss ttt uuu
jjj kkk lll mmm ooo ppp qqq
iii kkk jjj mmm lll mmm ooo
aaa bbb ddd fff ggg hhh ggg
sss ttt uuu ttt www xxx yyy
lll ooo ppp ooo rrr qqq sss



## 8.2.2 Train Word Embeddings from our simple language - naive version
Now we are using a simple implementation to train Word Embeddings. Try to fill in the gaps "______" in the code below to solve this excercise.

In [ ]:
def train_word_embedding_model(training_corpus, EMBEDDING_DIM = 10, EPOCHS = 300, CONTEXT_SIZE = 2):
  test_sentence = training_corpus.split()


  # we should tokenize the input, but we will ignore that for now
  # build a list of tuples.  Each tuple is ([ word_i-2, word_i-1 ], target word)
  trigrams = [([test_sentence[i-1], test_sentence[i + 1]], test_sentence[i ])
              for i in range(1,len(test_sentence) - 1)]
  # print the first 3, just so you can see what they look like
  print(trigrams[:3])

  # deduplicate 
  vocab = set(test_sentence)

  # generate the word index
  word_to_ix = {word: i for i, word in enumerate(vocab)}


  class NGramLanguageModeler(nn.Module):

      def __init__(self, vocab_size, embedding_dim, context_size):
          super(NGramLanguageModeler, self).__init__()
          self.embeddings = nn.Embedding(vocab_size, embedding_dim)
          self.linear1 = nn.Linear(context_size * embedding_dim, 128)
          self.linear2 = nn.Linear(128, vocab_size)

      def forward(self, inputs):
          embeds = self.embeddings(inputs).view((1, -1))
          out = F.relu(self.linear1(embeds))
          out = self.linear2(out)
          log_probs = F.log_softmax(out, dim=1)
          return log_probs


  losses = []
  loss_function = nn.NLLLoss()
  model = NGramLanguageModeler(len(vocab), EMBEDDING_DIM, CONTEXT_SIZE)

  # Exercise: What do SGD and lr mean? What happenes if you change them?
  optimizer = optim.SGD(model.parameters(), lr=0.001)


  for epoch in tqdm.tqdm(range(EPOCHS),total=EPOCHS):
      total_loss = 0
      for context, target in trigrams:

          # Step 1. Prepare the inputs to be passed to the model (i.e, turn the words
          # into integer indices and wrap them in tensors)
          context_idxs = torch.tensor([word_to_ix[w] for w in context], dtype=torch.long)

          # Step 2. Recall that torch *accumulates* gradients. Before passing in a
          # new instance, you need to zero out the gradients from the old
          # instance
          model.zero_grad()

          # Step 3. Run the forward pass, getting log probabilities over next
          # words
          log_probs = model(context_idxs)

          # Step 4. Compute your loss function. (Again, Torch wants the target
          # word wrapped in a tensor)
          loss = loss_function(log_probs, torch.tensor([word_to_ix[target]], dtype=torch.long))

          # Step 5. Do the backward pass and update the gradient
          loss.backward()
          optimizer.step()

          # Get the Python number from a 1-element Tensor by calling tensor.item()
          total_loss += loss.item()

      #print("\t", total_loss)
      losses.append(total_loss)
  print(losses) # The loss decreased every iteration over the training data!

  return model, word_to_ix, losses
training_corpus = generate_simple_language_corpus(SENTENCE_NUMBER=500, SENTENCE_LENGTH=7)
model, word_to_ix, losses = train_word_embedding_model(training_corpus, EMBEDDING_DIM=5, EPOCHS=10, CONTEXT_SIZE = 2)

EMBEDDING_DIM:  5
SEN_NUM:  500
EPOCHS:  200


100%|██████████| 200/200 [05:12<00:00,  1.56s/it]

[10306.665680885315, 8795.842024445534, 7926.520627558231, 7374.788049757481, 6998.806492030621, 6720.31259137392, 6498.815441071987, 6314.494820743799, 6157.607008039951, 6021.004434674978, 5900.6817862689495, 5793.660476505756, 5697.22221532464, 5609.6908395290375, 5529.451138317585, 5455.260790318251, 5385.987034112215, 5320.99150377512, 5259.886064872146, 5202.21263371408, 5147.787080347538, 5096.057380720973, 5047.113083690405, 5000.70173612237, 4956.634393393993, 4914.830408543348, 4875.052357003093, 4837.006602317095, 4800.582947313786, 4765.855749800801, 4732.679603725672, 4700.910161778331, 4670.525296494365, 4641.351919069886, 4613.222907975316, 4586.0758541077375, 4559.799787521362, 4534.428732305765, 4509.874261647463, 4486.218099460006, 4463.388217791915, 4441.253765180707, 4419.738439396024, 4398.881995782256, 4378.731051206589, 4359.129873290658, 4340.081370353699, 4321.4973611831665, 4303.425154939294, 4285.932430967689, 4269.03170453012, 4252.461120530963, 4236.5261309

# 8.2.3 Work with our Word-Embeddings
Now we are going to analyse how good our word embeddings were. For that we define first a function returning us the word embedding for a given word, and then a function sorting all word embeddings after their similarity to our target word.

Can you tweak the parameters from the word-embedding generation function to produce better results?

In [ ]:
def get_word_embedding_for_word(word_to_test, word_to_ix):
  word_to_test_ix = word_to_ix[word_to_test]
  word_to_test_torch = torch.tensor([word_to_test_ix], dtype=torch.long)
  
  embedding_of_word_to_test = model.embeddings(word_to_test_torch)
  return embedding_of_word_to_test

def most_similar(word_to_test, word_to_ix):
  test_embedding = get_word_embedding_for_word(word_to_test, word_to_ix)

  # get embeddings for all other possible words like aaa bbb ccc
  cos = torch.nn.CosineSimilarity()
  results = {}
  for c in string.ascii_lowercase:
    c_embedding = get_word_embedding_for_word(c+c+c, word_to_ix)

    cosine_similarity = cos(test_embedding, c_embedding)
    results[c+c+c] = cosine_similarity.item()
  sorted_results =  dict(sorted(results.items(), key=lambda item: -item[1]))
  return sorted_results

sims = most_similar("eee", word_to_ix)

for k,v in sims.items():
  print("{}: {}".format(k,v))

eee: 1.0
hhh: 0.408682644367218
aaa: 0.33671995997428894
ppp: 0.15390297770500183
xxx: 0.12604454159736633
zzz: 0.10617038607597351
nnn: 0.06814315170049667
uuu: 0.038116198033094406
fff: 0.031432054936885834
mmm: -0.019169578328728676
jjj: -0.06592382490634918
vvv: -0.1929464191198349
rrr: -0.29188206791877747
yyy: -0.31268852949142456
kkk: -0.32156622409820557
www: -0.4094087481498718
ccc: -0.41429662704467773
iii: -0.4157615900039673
ttt: -0.42468011379241943
lll: -0.45957136154174805
qqq: -0.48173922300338745
ddd: -0.5246429443359375
ggg: -0.5451634526252747
ooo: -0.5874466300010681
bbb: -0.6789381504058838
sss: -0.8591558933258057


## 8.2.4 Better Implementation
We are using now our generated simple language and a much more optimized implementation of word-embeddings, the ones in the library [gensim](https://radimrehurek.com/gensim/).

Again we are displaying the most similar vectors. Can you notice a difference in performance to our naive implementation?

In [ ]:
import gensim 
from sklearn.decomposition import PCA 
from matplotlib import pyplot 

import warnings 
warnings.filterwarnings('ignore') 

training_corpus =  generate_simple_language_corpus(SENTENCE_NUMBER=3000, SENTENCE_LENGTH=7)

# we have to convert the corpus to a different form for gensim
training_corpus_gensim = [w.split(" ") for w in training_corpus.split("\n")]


model = gensim.models.Word2Vec(training_corpus_gensim, window=2) 

model.most_similar('ccc')

[('ddd', 0.9979580640792847),
 ('bbb', 0.993108868598938),
 ('eee', 0.9924113750457764),
 ('jjj', 0.9917413592338562),
 ('kkk', 0.991080105304718),
 ('iii', 0.9904963970184326),
 ('ggg', 0.9902485013008118),
 ('hhh', 0.9890344738960266),
 ('fff', 0.9880383014678955),
 ('aaa', 0.9762473702430725)]

# Lesson 8.3: Use existing embeddings

Now we are using already pre-trained word embeddings.
The code below exemplifies how to load a trained embedding model in the gensim library. 

In [ ]:
# Let's first load a small subset of word2vec embeddings that have been trained on a 
# large corpus of news documents  
!wget https://github.com/dgromann/SemanticComputing/raw/master/tutorial6/word2vec_embeddings.bin
!wget https://raw.githubusercontent.com/dgromann/SemComp_WS2018/master/Tutorial6/analogy.txt


--2022-01-11 11:01:21--  https://github.com/dgromann/SemanticComputing/raw/master/tutorial6/word2vec_embeddings.bin
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dgromann/SemanticComputing/master/tutorial6/word2vec_embeddings.bin [following]
--2022-01-11 11:01:21--  https://raw.githubusercontent.com/dgromann/SemanticComputing/master/tutorial6/word2vec_embeddings.bin
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96769269 (92M) [application/octet-stream]
Saving to: ‘word2vec_embeddings.bin.1’

word2vec_embeddings 100%[===================>]  92.29M   219MB/s    in 0.4s    

2022-01-11 11:01

In [ ]:
import gensim
from sklearn.decomposition import PCA
from matplotlib import pyplot

import warnings
warnings.filterwarnings('ignore')

In [81]:
# Let's load the model
model = gensim.models.KeyedVectors.load_word2vec_format("word2vec_embeddings.bin", binary=True)

# Print the length fo the whole vocabulary 
print(len(model.wv.vocab))

# Print the embedding of a specific word 
print(model["good"])

# Get the 10 most similar words of "good"
print(model.most_similar("good", topn=10))

# Check whether our embeddings are good at the analogy task
print(model.most_similar(positive=['women', 'king'], negative=['man'], topn=1))

80000
[ 0.04052734  0.0625     -0.01745605  0.07861328  0.03271484 -0.01263428
  0.00964355  0.12353516 -0.02148438  0.15234375 -0.05834961 -0.10644531
  0.02124023  0.13574219 -0.13183594  0.17675781  0.27148438  0.13769531
 -0.17382812 -0.14160156 -0.03076172  0.19628906 -0.03295898  0.125
  0.25390625  0.12695312 -0.15234375  0.03198242  0.01135254 -0.01361084
 -0.12890625  0.01019287  0.23925781 -0.08447266  0.140625    0.13085938
 -0.04516602  0.06494141  0.02539062  0.05615234  0.24609375 -0.20507812
  0.23632812 -0.00860596 -0.02294922  0.05078125  0.10644531 -0.03564453
  0.08740234 -0.05712891  0.08496094  0.23535156 -0.10107422 -0.03564453
 -0.04736328  0.04736328 -0.14550781 -0.10986328  0.14746094 -0.23242188
 -0.07275391  0.19628906 -0.37890625 -0.07226562  0.04833984  0.11914062
  0.06103516 -0.12109375 -0.27929688  0.05200195  0.04907227 -0.02709961
  0.1328125   0.03369141 -0.32226562  0.04223633 -0.08789062  0.15429688
  0.09472656  0.10351562 -0.02856445  0.00128174 -